[package]
name = "helcli"
version = "0.1.0"
authors = ["ok2"]
edition = "2021"

[[bin]]
name = "hel"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hel = { version = "0.1.0", path = "../hel" }
rustyline = "10.0.0"
